-- Sample data for initial setup - Multi-tenant POS System
-- Note: Since entities use GenerationType.UUID, IDs are generated by JPA
-- This data.sql is for reference - actual data should be created via DataInitializer

-- Insert sample tenants
INSERT INTO tenants (id, name, subdomain, description, company_name, contact_email, contact_phone, max_users, current_user_count, active, subscription_plan, subscription_expires, created_at, updated_at) VALUES
('550e8400-e29b-41d4-a716-446655440001', 'Demo Store', 'demo', 'Demo retail store for testing', 'Demo Retail Inc.', 'admin@demo.com', '5551234567', 50, 3, true, 'PROFESSIONAL', '2027-05-01 00:00:00', NOW(), NOW()),
('550e8400-e29b-41d4-a716-446655440002', 'Tech Shop', 'techshop', 'Technology and electronics store', 'Tech Shop LLC', 'contact@techshop.com', '5559876543', 25, 0, true, 'BASIC', '2026-11-01 00:00:00', NOW(), NOW()),
('550e8400-e29b-41d4-a716-446655440003', 'Fashion Hub', 'fashion', 'Fashion and clothing boutique', 'Fashion Hub', 'info@fashion.com', '5554567890', 100, 0, false, 'ENTERPRISE', '2028-05-01 00:00:00', NOW(), NOW());

-- Insert sample tenant permissions for demo tenant
INSERT INTO tenant_permissions (id, tenant_id, permission_name, description, enabled, created_at, updated_at) VALUES
('660e8400-e29b-41d4-a716-446655440001', '550e8400-e29b-41d4-a716-446655440001', 'VIEW_PRODUCTS', 'View products', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440002', '550e8400-e29b-41d4-a716-446655440001', 'CREATE_PRODUCTS', 'Create products', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440003', '550e8400-e29b-41d4-a716-446655440001', 'UPDATE_PRODUCTS', 'Update products', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440004', '550e8400-e29b-41d4-a716-446655440001', 'DELETE_PRODUCTS', 'Delete products', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440005', '550e8400-e29b-41d4-a716-446655440001', 'VIEW_CATEGORIES', 'View categories', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440006', '550e8400-e29b-41d4-a716-446655440001', 'CREATE_CATEGORIES', 'Create categories', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440007', '550e8400-e29b-41d4-a716-446655440001', 'UPDATE_CATEGORIES', 'Update categories', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440008', '550e8400-e29b-41d4-a716-446655440001', 'DELETE_CATEGORIES', 'Delete categories', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440009', '550e8400-e29b-41d4-a716-446655440001', 'VIEW_CUSTOMERS', 'View customers', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440010', '550e8400-e29b-41d4-a716-446655440001', 'CREATE_CUSTOMERS', 'Create customers', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440011', '550e8400-e29b-41d4-a716-446655440001', 'UPDATE_CUSTOMERS', 'Update customers', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440012', '550e8400-e29b-41d4-a716-446655440001', 'DELETE_CUSTOMERS', 'Delete customers', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440013', '550e8400-e29b-41d4-a716-446655440001', 'VIEW_SALES', 'View sales', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440014', '550e8400-e29b-41d4-a716-446655440001', 'CREATE_SALES', 'Create sales', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440015', '550e8400-e29b-41d4-a716-446655440001', 'REFUND_SALES', 'Refund sales', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440016', '550e8400-e29b-41d4-a716-446655440001', 'VIEW_ANALYTICS', 'View analytics', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440017', '550e8400-e29b-41d4-a716-446655440001', 'VIEW_REPORTS', 'View reports', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440018', '550e8400-e29b-41d4-a716-446655440001', 'MANAGE_USERS', 'Manage users', true, NOW(), NOW()),
('660e8400-e29b-41d4-a716-446655440019', '550e8400-e29b-41d4-a716-446655440001', 'MANAGE_PERMISSIONS', 'Manage permissions', true, NOW(), NOW());

-- Insert sample users (associated with demo tenant)
INSERT INTO users (id, username, password, email, is_verified, first_name, last_name, phone_number, role, enabled, tenant_id, created_at, updated_at) VALUES
('770e8400-e29b-41d4-a716-446655440001', 'admin', '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.', 'admin@demo.com', true, 'Admin', 'User', '1234567890', 'ADMIN', true, '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('770e8400-e29b-41d4-a716-446655440002', 'manager', '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.', 'manager@demo.com', true, 'Manager', 'User', '1234567891', 'MANAGER', true, '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('770e8400-e29b-41d4-a716-446655440003', 'cashier', '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.', 'cashier@demo.com', true, 'Cashier', 'User', '1234567892', 'CASHIER', true, '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW());

-- Insert sample categories (associated with demo tenant)
INSERT INTO categories (id, name, description, image_url, active, tenant_id, created_at, updated_at) VALUES
('880e8400-e29b-41d4-a716-446655440001', 'Electronics', 'Electronic devices and accessories', NULL, true, '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('880e8400-e29b-41d4-a716-446655440002', 'Clothing', 'Apparel and fashion items', NULL, true, '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('880e8400-e29b-41d4-a716-446655440003', 'Food & Beverages', 'Food items and drinks', NULL, true, '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('880e8400-e29b-41d4-a716-446655440004', 'Books', 'Books and educational materials', NULL, true, '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('880e8400-e29b-41d4-a716-446655440005', 'Home & Garden', 'Home improvement and garden supplies', NULL, true, '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW());

-- Insert sample products (associated with demo tenant)
INSERT INTO products (id, name, description, sku, price, quantity, min_quantity, max_quantity, cost_price, image_url, active, category_id, tenant_id, created_at, updated_at) VALUES
('990e8400-e29b-41d4-a716-446655440001', 'Laptop Pro 15"', 'High-performance laptop with 15-inch display', 'LAP001', 999.99, 25, 5, 100, 750.00, 'https://example.com/laptop.jpg', true, '880e8400-e29b-41d4-a716-446655440001', '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('990e8400-e29b-41d4-a716-446655440002', 'Wireless Mouse', 'Ergonomic wireless mouse', 'MOU001', 29.99, 50, 10, 200, 15.00, 'https://example.com/mouse.jpg', true, '880e8400-e29b-41d4-a716-446655440001', '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('990e8400-e29b-41d4-a716-446655440003', 'T-Shirt Cotton', '100% cotton t-shirt', 'TSH001', 19.99, 100, 20, 500, 8.00, 'https://example.com/tshirt.jpg', true, '880e8400-e29b-41d4-a716-446655440002', '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('990e8400-e29b-41d4-a716-446655440004', 'Jeans Classic', 'Classic fit denim jeans', 'JEA001', 49.99, 40, 10, 150, 25.00, 'https://example.com/jeans.jpg', true, '880e8400-e29b-41d4-a716-446655440002', '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('990e8400-e29b-41d4-a716-446655440005', 'Coffee Beans', 'Premium arabica coffee beans', 'COF001', 12.99, 200, 50, 1000, 6.50, 'https://example.com/coffee.jpg', true, '880e8400-e29b-41d4-a716-446655440003', '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('990e8400-e29b-41d4-a716-446655440006', 'Mineral Water', 'Natural mineral water 1L', 'WAT001', 1.99, 300, 100, 2000, 0.80, 'https://example.com/water.jpg', true, '880e8400-e29b-41d4-a716-446655440003', '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('990e8400-e29b-41d4-a716-446655440007', 'Programming Guide', 'Complete programming guide book', 'BOO001', 39.99, 30, 5, 100, 20.00, 'https://example.com/book.jpg', true, '880e8400-e29b-41d4-a716-446655440004', '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('990e8400-e29b-41d4-a716-446655440008', 'Garden Tools Set', 'Complete garden tool set', 'GAR001', 79.99, 15, 3, 50, 45.00, 'https://example.com/tools.jpg', true, '880e8400-e29b-41d4-a716-446655440005', '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW());

-- Insert sample customers (associated with demo tenant)
INSERT INTO customers (id, name, email, phone_number, address, loyalty_points, active, tenant_id, created_at, updated_at) VALUES
('aa0e8400-e29b-41d4-a716-446655440001', 'John Doe', 'john.doe@email.com', '5551234567', '123 Main St, City, State', 150, true, '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('aa0e8400-e29b-41d4-a716-446655440002', 'Jane Smith', 'jane.smith@email.com', '5559876543', '456 Oak Ave, City, State', 75, true, '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('aa0e8400-e29b-41d4-a716-446655440003', 'Bob Johnson', 'bob.johnson@email.com', '5554567890', '789 Pine Rd, City, State', 200, true, '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('aa0e8400-e29b-41d4-a716-446655440004', 'Alice Brown', 'alice.brown@email.com', '5552345678', '321 Elm St, City, State', 50, true, '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW()),
('aa0e8400-e29b-41d4-a716-446655440005', 'Charlie Wilson', 'charlie.wilson@email.com', '5553456789', '654 Maple Dr, City, State', 300, true, '550e8400-e29b-41d4-a716-446655440001', NOW(), NOW());
